### ISSUE TITLE
Get the error message below

### ISSUE THREAD

**Issue by jstrebel** [RE0x2A/geojson.io-for-vscode#1]
[{
	"resource": "/c:/Users/jakob/Desktop/str_chnebel_10mrz/str_chnebel_2_myg.geojson",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "768",
	"severity": 4,
	"message": "Unable to load schema from 'https://geojson.org/schema/GeoJSON.json': certificate has expired.",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]

**Comment by 42arch** [comment]
Hey Jakob, can you give me more information about this error? like when and where this error occurs.
