### ISSUE TITLE
Suggestion for a new feature

### ISSUE THREAD

**Issue by Schiffsradar** [RE0x2A/geojson.io-for-vscode#29]
Hi rend,

Could you consider adding another function? I have seen the function in the editor of "geoman.io" and it is very helpful. The function looks like this:

Imagine that a marker already exists on the map. Now I want to manually draw a new polyline. But the start point/end point of the polyline should have exactly the coordinates of the existing marker. When I move the mouse pointer close to the marker, the existing marker should be found automatically. (Like a magnet, the mouse pointer is attracted) Thus, start points/end points or also corner points can be set exactly congruent.

What do you think about this feature?

**Comment by 42arch** [comment]
Thanks for your suggestion! It sounds great, I didn't consider this situation before. I'll add this feature in next big version update.
