### ISSUE TITLE
command 'geojson-io-forvscode.openMap' not found

### ISSUE THREAD

**Issue by fedderw** [RE0x2A/geojson.io-for-vscode#30]
![image](https://user-images.githubusercontent.com/16396180/190940107-58c3e9c5-8b65-4b10-b3fb-22b76d35853d.png)

I'm getting this error on WSL. I tried downgrading to a previous version, but no luck.

**Comment by 42arch** [comment]
Have you tried downgrading to version 0.4.3? There are some problems in current version, I'm fixing it.

**Comment by fedderw** [comment]
> Have you tried downgrading to version 0.4.3? There are some problems in current version, I'm fixing it.

This works now!

**Comment by fedderw** [comment]
I just updated to the newest version - it's working now! Thanks
